### ISSUE TITLE
Slack channel 

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/proxi-schemas#11]
@edeutsch @jjcarver Shin, Nuno and Juan do we want to have an open channel in slack that enable use to talk about the project daily basics for example. Also this can be open to other collaborators to interact with the group/project. 

We have been using this strategy in other projects such as Biocontainers and people join making questions and proposing features for the resource.

**Comment by edeutsch** [comment]
I am willing to try this. I am on slack for some other projects. However, in general, I am not a big fan. I find it a bit difficult to follow all these different sources of interruption. I would prefer to try GitHub team discussions first to see if that works because we're all finally together on GitHub, so starting something else on another platform seems sub-optimal.

**Comment by ypriverol** [comment]
Ok we close this
