### ISSUE TITLE
Include in the specification the attributes that would be REQUIRED

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/proxi-schemas#46]
We should have a list of REQUIRED fields and how we express them into `spectra`.

**Comment by edeutsch** [comment]
At the moment only resultType is required. Which is weird because we haven't defined how different resultTypes would look like? But fine, I suppose we said that should be required for all.

It doesn't seem like we can require anything else.
- For some queries, usi= is sufficient (plus resultType I suppose)
- For other queries, accession+msRun+scan is equivalent to a USI (partly)
- Those two are mutually exclusive or at least redundant.

So I would rather focus on learning what individual resources *can* support rather than imposing requirements at this stage.

**Comment by ypriverol** [comment]
Here the first list of attributes we can try to standarize across all implementations: 

https://github.com/HUPO-PSI/proxi-schemas/pull/48
